-- V2.5.119B — senior/operator manual dublis override at any phase.
create table if not exists public.weekend_backup_override_audit_v25119(
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null,
  target_initials text not null,
  actor_user_id uuid,
  actor_initials text,
  reason text not null,
  before_json jsonb,
  after_json jsonb,
  created_at timestamptz not null default now()
);
alter table public.weekend_backup_override_audit_v25119 enable row level security;
drop policy if exists "backup override audit operator read" on public.weekend_backup_override_audit_v25119;
create policy "backup override audit operator read" on public.weekend_backup_override_audit_v25119
for select to authenticated using(public.is_lifecycle_operator_v2592(auth.uid()));
revoke insert,update,delete on public.weekend_backup_override_audit_v25119 from authenticated,anon;
grant select on public.weekend_backup_override_audit_v25119 to authenticated;

create or replace function public.operator_set_weekend_backup_v25119(
  p_year integer,p_month integer,p_target_initials text,p_covered_slot integer,p_reason text
)
returns jsonb
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare
  v_actor text; v_target public.weekend_backup_claims%rowtype; v_owner public.weekend_backup_claims%rowtype;
  v_slot public.weekend_backup_slot_catalog_v25119%rowtype;
  v_old_slot public.weekend_backup_slot_catalog_v25119%rowtype;
  v_before jsonb; v_after jsonb;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  select initials into v_actor from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_actor is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  if coalesce(trim(p_reason),'')='' then raise exception 'BACKUP_OVERRIDE_REASON_REQUIRED'; end if;
  if not exists(select 1 from public.resident_directory where initials=p_target_initials and coalesce(active,true)=true)
    then raise exception 'UNKNOWN_OR_INACTIVE_RESIDENT'; end if;
  select * into v_slot from public.weekend_backup_slot_catalog_v25119
    where year=p_year and month=p_month and covered_slot=p_covered_slot and active=true;
  if not found then raise exception 'BACKUP_SLOT_OUTSIDE_16_SLOT_CATALOG'; end if;

  perform pg_advisory_xact_lock(25121,p_year*100+p_month);
  select * into v_target from public.weekend_backup_claims
    where year=p_year and month=p_month and initials=p_target_initials for update;
  select * into v_owner from public.weekend_backup_claims
    where year=p_year and month=p_month and covered_slot=p_covered_slot for update;

  v_before:=jsonb_build_object('target',to_jsonb(v_target),'slot_owner',to_jsonb(v_owner));

  if v_owner.id is not null and v_owner.initials is distinct from p_target_initials then
    if v_target.id is null then
      raise exception 'TARGET_SLOT_ALREADY_OWNED';
    end if;
    select * into v_old_slot from public.weekend_backup_slot_catalog_v25119
      where year=p_year and month=p_month and covered_slot=v_target.covered_slot and active=true;
    if v_old_slot.covered_slot is null then raise exception 'TARGET_OLD_SLOT_NOT_IN_CATALOG'; end if;
    update public.weekend_backup_claims
      set covered_slot=v_old_slot.covered_slot,claim_day=v_old_slot.claim_day,claim_block=v_old_slot.claim_block,
          source='operator_manual_swap',updated_at=now()
      where id=v_owner.id;
  end if;

  if v_target.id is null then
    insert into public.weekend_backup_claims(year,month,covered_slot,initials,source,claimed_at,updated_at,claim_day,claim_block)
    values(p_year,p_month,v_slot.covered_slot,p_target_initials,'operator_manual',now(),now(),v_slot.claim_day,v_slot.claim_block);
  else
    update public.weekend_backup_claims
      set covered_slot=v_slot.covered_slot,claim_day=v_slot.claim_day,claim_block=v_slot.claim_block,
          source='operator_manual',updated_at=now()
      where id=v_target.id;
  end if;

  select jsonb_build_object(
    'target',(select to_jsonb(w) from public.weekend_backup_claims w where w.year=p_year and w.month=p_month and w.initials=p_target_initials),
    'slot_owner',(select to_jsonb(w) from public.weekend_backup_claims w where w.year=p_year and w.month=p_month and w.covered_slot=p_covered_slot)
  ) into v_after;

  insert into public.weekend_backup_override_audit_v25119(year,month,target_initials,actor_user_id,actor_initials,reason,before_json,after_json)
  values(p_year,p_month,p_target_initials,auth.uid(),v_actor,trim(p_reason),v_before,v_after);
  return jsonb_build_object('ok',true,'before',v_before,'after',v_after);
end;
$$;
grant execute on function public.operator_set_weekend_backup_v25119(integer,integer,text,integer,text) to authenticated;
