-- V2.5.123 — SP private privileged pair wishes.
-- Intentionally isolated from ordinary resident preferences and public audit tables.

create table if not exists public.sp_private_pair_preferences_v25123 (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null check (month between 1 and 12),
  preference_type text not null check (preference_type in ('together','apart')),
  target_initials text not null references public.resident_directory(initials) on delete cascade,
  scope_type text not null check (scope_type in ('month','week','day')),
  scope_start_date date null,
  block text not null default 'ANY' check (block in ('ANY','AM','PM')),
  workplace text not null default 'ANY' check (workplace in ('ANY','CENTRO RO','Onko RO','SPS RO','Centro UG','SPS UG','ADC 144','ADC 145','Vaikų UG','Mamografijos')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (target_initials <> 'SP'),
  check (
    (scope_type='month' and scope_start_date is null)
    or (scope_type in ('week','day') and scope_start_date is not null)
  )
);

create index if not exists idx_sp_private_pair_preferences_month_v25123
  on public.sp_private_pair_preferences_v25123(year,month);

create table if not exists public.sp_private_pair_preference_audit_v25123 (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null,
  actor_user_id uuid null,
  actor_initials text not null,
  action text not null check (action in ('create','delete')),
  preference_id bigint null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.sp_private_pair_preferences_v25123 enable row level security;
alter table public.sp_private_pair_preference_audit_v25123 enable row level security;

drop policy if exists "sp private pair prefs select" on public.sp_private_pair_preferences_v25123;
create policy "sp private pair prefs select" on public.sp_private_pair_preferences_v25123
for select to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
);

drop policy if exists "sp private pair prefs insert" on public.sp_private_pair_preferences_v25123;
create policy "sp private pair prefs insert" on public.sp_private_pair_preferences_v25123
for insert to authenticated
with check (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
);

drop policy if exists "sp private pair prefs update" on public.sp_private_pair_preferences_v25123;
create policy "sp private pair prefs update" on public.sp_private_pair_preferences_v25123
for update to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
)
with check (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
);

drop policy if exists "sp private pair prefs delete" on public.sp_private_pair_preferences_v25123;
create policy "sp private pair prefs delete" on public.sp_private_pair_preferences_v25123
for delete to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
);

drop policy if exists "sp private pair audit select" on public.sp_private_pair_preference_audit_v25123;
create policy "sp private pair audit select" on public.sp_private_pair_preference_audit_v25123
for select to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials='SP'
  )
);

create or replace function public.sp_create_private_pair_preference_v25123(
  p_year integer,
  p_month integer,
  p_preference_type text,
  p_target_initials text,
  p_scope_type text,
  p_scope_start_date date,
  p_block text,
  p_workplace text
)
returns public.sp_private_pair_preferences_v25123
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare
  v_uid uuid:=auth.uid();
  v_actor text;
  v_row public.sp_private_pair_preferences_v25123%rowtype;
  v_month_start date:=make_date(p_year,p_month,1);
  v_month_end date:=(make_date(p_year,p_month,1)+interval '1 month - 1 day')::date;
begin
  select up.initials into v_actor
  from public.user_profiles up
  where up.user_id=v_uid and up.approved=true
  limit 1;
  if v_actor is distinct from 'SP' then raise exception 'SP_PRIVATE_PREFERENCE_ONLY'; end if;
  if p_target_initials='SP' or not exists(
      select 1 from public.resident_directory rd where rd.initials=p_target_initials and coalesce(rd.active,true)=true
  ) then raise exception 'INVALID_PRIVATE_PAIR_TARGET'; end if;
  if p_preference_type not in ('together','apart') then raise exception 'INVALID_PRIVATE_PAIR_TYPE'; end if;
  if p_scope_type not in ('month','week','day') then raise exception 'INVALID_PRIVATE_PAIR_SCOPE'; end if;
  if coalesce(p_block,'ANY') not in ('ANY','AM','PM') then raise exception 'INVALID_PRIVATE_PAIR_BLOCK'; end if;
  if coalesce(p_workplace,'ANY') not in ('ANY','CENTRO RO','Onko RO','SPS RO','Centro UG','SPS UG','ADC 144','ADC 145','Vaikų UG','Mamografijos') then
    raise exception 'INVALID_PRIVATE_PAIR_WORKPLACE';
  end if;
  if p_scope_type='month' and p_scope_start_date is not null then raise exception 'MONTH_SCOPE_DATE_MUST_BE_NULL'; end if;
  if p_scope_type in ('week','day') then
    if p_scope_start_date is null then raise exception 'PRIVATE_PAIR_SCOPE_DATE_REQUIRED'; end if;
    if p_scope_start_date < v_month_start or p_scope_start_date > v_month_end then raise exception 'PRIVATE_PAIR_SCOPE_DATE_OUTSIDE_MONTH'; end if;
  end if;

  insert into public.sp_private_pair_preferences_v25123(
    year,month,preference_type,target_initials,scope_type,scope_start_date,block,workplace
  ) values(
    p_year,p_month,p_preference_type,p_target_initials,p_scope_type,p_scope_start_date,
    coalesce(p_block,'ANY'),coalesce(p_workplace,'ANY')
  ) returning * into v_row;

  insert into public.sp_private_pair_preference_audit_v25123(
    year,month,actor_user_id,actor_initials,action,preference_id,payload
  ) values(
    p_year,p_month,v_uid,v_actor,'create',v_row.id,to_jsonb(v_row)
  );
  return v_row;
end;
$$;

create or replace function public.sp_delete_private_pair_preference_v25123(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare
  v_uid uuid:=auth.uid();
  v_actor text;
  v_row public.sp_private_pair_preferences_v25123%rowtype;
begin
  select up.initials into v_actor
  from public.user_profiles up
  where up.user_id=v_uid and up.approved=true
  limit 1;
  if v_actor is distinct from 'SP' then raise exception 'SP_PRIVATE_PREFERENCE_ONLY'; end if;
  select * into v_row from public.sp_private_pair_preferences_v25123 where id=p_id for update;
  if not found then return false; end if;
  delete from public.sp_private_pair_preferences_v25123 where id=p_id;
  insert into public.sp_private_pair_preference_audit_v25123(
    year,month,actor_user_id,actor_initials,action,preference_id,payload
  ) values(
    v_row.year,v_row.month,v_uid,v_actor,'delete',v_row.id,to_jsonb(v_row)
  );
  return true;
end;
$$;

-- Lifecycle operators may learn only WHETHER a private SP preference exists.
-- Target names, scopes and details remain unavailable unless the caller is SP.
create or replace function public.sp_private_pair_preferences_exist_v25123(p_year integer,p_month integer)
returns boolean
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $$
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then
    return false;
  end if;
  return exists(
    select 1 from public.sp_private_pair_preferences_v25123
    where year=p_year and month=p_month
  );
end;
$$;

grant execute on function public.sp_create_private_pair_preference_v25123(integer,integer,text,text,text,date,text,text) to authenticated;
grant execute on function public.sp_delete_private_pair_preference_v25123(bigint) to authenticated;
grant execute on function public.sp_private_pair_preferences_exist_v25123(integer,integer) to authenticated;

grant select on table public.sp_private_pair_preferences_v25123 to authenticated;
grant select on table public.sp_private_pair_preference_audit_v25123 to authenticated;

create unique index if not exists sp_private_pair_pref_unique_v25123
on public.sp_private_pair_preferences_v25123(
  year,month,preference_type,target_initials,scope_type,
  coalesce(scope_start_date,date '1900-01-01'),block,workplace
);
