-- V2.5.97 senior-only operational day-status markers.
create table if not exists public.schedule_day_statuses (
    id bigint generated by default as identity primary key,
    year integer not null check (year between 2020 and 2100),
    month integer not null check (month between 1 and 12),
    day integer not null check (day between 1 and 31),
    initials text not null references public.resident_directory(initials),
    status_kind text not null check (status_kind in ('sick_leave','qualification','wellness')),
    note text not null default '',
    created_by uuid not null default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(year,month,day,initials)
);

alter table public.schedule_day_statuses enable row level security;

drop policy if exists "schedule day status lifecycle operator read" on public.schedule_day_statuses;
create policy "schedule day status lifecycle operator read"
on public.schedule_day_statuses for select
to authenticated
using (public.is_lifecycle_operator_v2592(auth.uid()));

drop policy if exists "schedule day status lifecycle operator write" on public.schedule_day_statuses;
create policy "schedule day status lifecycle operator write"
on public.schedule_day_statuses for all
to authenticated
using (public.is_lifecycle_operator_v2592(auth.uid()))
with check (public.is_lifecycle_operator_v2592(auth.uid()));

create or replace function public.set_schedule_day_status_v2597(
    p_year integer, p_month integer, p_day integer,
    p_initials text, p_status_kind text, p_note text default ''
) returns public.schedule_day_statuses
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    outrow public.schedule_day_statuses;
begin
    if not public.is_lifecycle_operator_v2592(auth.uid()) then
        raise exception 'Not authorized';
    end if;
    if p_status_kind not in ('sick_leave','qualification','wellness') then
        raise exception 'Invalid status kind';
    end if;
    if p_day < 1 or p_day > extract(day from (date_trunc('month',make_date(p_year,p_month,1)) + interval '1 month - 1 day'))::int then
        raise exception 'Invalid day for month';
    end if;
    insert into public.schedule_day_statuses(year,month,day,initials,status_kind,note,created_by,created_at,updated_at)
    values(p_year,p_month,p_day,p_initials,p_status_kind,coalesce(p_note,''),auth.uid(),now(),now())
    on conflict(year,month,day,initials) do update
      set status_kind=excluded.status_kind,
          note=excluded.note,
          updated_at=now()
    returning * into outrow;
    return outrow;
end;
$$;

create or replace function public.clear_schedule_day_status_v2597(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if not public.is_lifecycle_operator_v2592(auth.uid()) then
        raise exception 'Not authorized';
    end if;
    delete from public.schedule_day_statuses where id=p_id;
    return found;
end;
$$;

grant execute on function public.set_schedule_day_status_v2597(integer,integer,integer,text,text,text) to authenticated;
grant execute on function public.clear_schedule_day_status_v2597(bigint) to authenticated;
