-- V2.5.110 — persistent WESTON beer click ledger for the operational senior scheduler.
-- One press of the main GENERATE / REGENERATE button by SR = one WESTON beer.
-- Additive only; no schedule, preference, fairness or research data is modified.

create table if not exists public.weston_beer_ledger_v25110 (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    initials text not null references public.resident_directory(initials) on update cascade on delete cascade,
    cycle_year integer not null check (cycle_year between 2026 and 2100),
    cycle_month integer not null check (cycle_month between 1 and 12),
    action text not null default 'generate' check (action = 'generate'),
    created_at timestamptz not null default now(),
    check (initials = 'SR')
);

create index if not exists weston_beer_ledger_v25110_user_idx
    on public.weston_beer_ledger_v25110(user_id, created_at);
create index if not exists weston_beer_ledger_v25110_cycle_idx
    on public.weston_beer_ledger_v25110(cycle_year, cycle_month, created_at);

alter table public.weston_beer_ledger_v25110 enable row level security;

drop policy if exists weston_beer_ledger_v25110_self_select on public.weston_beer_ledger_v25110;
create policy weston_beer_ledger_v25110_self_select
on public.weston_beer_ledger_v25110 for select
to authenticated
using (user_id = auth.uid());

-- No direct INSERT/UPDATE/DELETE policy is created. Writes go only through the
-- authenticated SECURITY DEFINER function below, which verifies that auth.uid()
-- is the approved SR account.

create or replace function public.record_weston_beer_click_v25110(
    p_cycle_year integer,
    p_cycle_month integer
)
returns table(total_beers bigint, month_beers bigint)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_uid uuid := auth.uid();
    v_initials text;
begin
    if v_uid is null then
        raise exception 'AUTH_REQUIRED' using errcode='42501';
    end if;

    select up.initials into v_initials
    from public.user_profiles up
    where up.user_id = v_uid
      and up.approved = true
    limit 1;

    if v_initials is distinct from 'SR' then
        raise exception 'WESTON_LEDGER_SR_ONLY' using errcode='42501';
    end if;

    if p_cycle_year < 2026 or p_cycle_year > 2100 or p_cycle_month < 1 or p_cycle_month > 12 then
        raise exception 'INVALID_CYCLE';
    end if;

    insert into public.weston_beer_ledger_v25110(user_id, initials, cycle_year, cycle_month, action)
    values (v_uid, 'SR', p_cycle_year, p_cycle_month, 'generate');

    return query
    select
        count(*)::bigint as total_beers,
        count(*) filter (where w.cycle_year=p_cycle_year and w.cycle_month=p_cycle_month)::bigint as month_beers
    from public.weston_beer_ledger_v25110 w
    where w.user_id=v_uid;
end;
$$;

create or replace function public.weston_beer_stats_v25110(
    p_cycle_year integer,
    p_cycle_month integer
)
returns table(total_beers bigint, month_beers bigint)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_uid uuid := auth.uid();
    v_initials text;
begin
    if v_uid is null then
        raise exception 'AUTH_REQUIRED' using errcode='42501';
    end if;

    select up.initials into v_initials
    from public.user_profiles up
    where up.user_id = v_uid
      and up.approved = true
    limit 1;

    if v_initials is distinct from 'SR' then
        raise exception 'WESTON_LEDGER_SR_ONLY' using errcode='42501';
    end if;

    return query
    select
        count(*)::bigint as total_beers,
        count(*) filter (where w.cycle_year=p_cycle_year and w.cycle_month=p_cycle_month)::bigint as month_beers
    from public.weston_beer_ledger_v25110 w
    where w.user_id=v_uid;
end;
$$;

revoke all on function public.record_weston_beer_click_v25110(integer,integer) from public;
revoke all on function public.weston_beer_stats_v25110(integer,integer) from public;
grant execute on function public.record_weston_beer_click_v25110(integer,integer) to authenticated;
grant execute on function public.weston_beer_stats_v25110(integer,integer) to authenticated;
