-- V2.5.91 FINALIZATION WORKFLOW
-- DRAFT -> SWAP_OPEN -> SWAP_CLOSED -> FINAL
-- R.S. alone operates the lifecycle. R.Š. may retain other embedded admin rights.

create table if not exists public.schedule_lifecycle (
  year integer not null,
  month integer not null check (month between 1 and 12),
  state text not null default 'draft' check (state in ('draft','swap_open','swap_closed','final')),
  swap_opened_at timestamptz,
  swap_deadline timestamptz,
  swap_closed_at timestamptz,
  opened_by uuid,
  finalized_at timestamptz,
  finalized_by uuid,
  final_json jsonb,
  final_backups jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(year,month)
);

alter table public.schedule_lifecycle add column if not exists final_backups jsonb;

create table if not exists public.late_swap_access (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null check (month between 1 and 12),
  initials text not null references public.resident_directory(initials),
  access_mode text not null default 'one_request' check (access_mode in ('one_request','time_window')),
  max_requests integer not null default 1 check (max_requests between 1 and 20),
  requests_used integer not null default 0 check (requests_used>=0),
  expires_at timestamptz not null,
  reason text not null default '',
  granted_by uuid not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);
create index if not exists late_swap_access_month_idx on public.late_swap_access(year,month,initials,expires_at);

alter table public.schedule_lifecycle enable row level security;
alter table public.late_swap_access enable row level security;
drop policy if exists "schedule lifecycle authenticated read" on public.schedule_lifecycle;
create policy "schedule lifecycle authenticated read" on public.schedule_lifecycle for select to authenticated using (true);
drop policy if exists "late swap own or privileged read" on public.late_swap_access;
create policy "late swap own or privileged read" on public.late_swap_access for select to authenticated using (
  initials=(select up.initials from public.user_profiles up where up.user_id=auth.uid() and up.approved=true limit 1)
  or public.is_senior(auth.uid())
);

create or replace function public.is_operational_seniune_v2591(uid uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.user_profiles up
    where up.user_id=uid and up.approved=true and up.initials='R.S.'
  );
$$;

create or replace function public.open_swap_window_v2591(p_year integer,p_month integer,p_deadline timestamptz)
returns public.schedule_lifecycle language plpgsql security definer set search_path=public,auth as $$
declare v_row public.schedule_lifecycle%rowtype;
begin
  if not public.is_operational_seniune_v2591(auth.uid()) then raise exception 'OPERATIONAL_SENIUNE_REQUIRED'; end if;
  if p_deadline<=now() then raise exception 'SWAP_DEADLINE_MUST_BE_FUTURE'; end if;
  if not exists(select 1 from public.schedules s where s.year=p_year and s.month=p_month and s.status='published' and s.baseline_json is not null and s.current_json is not null) then
    raise exception 'PUBLISHED_SYSTEM_REQUIRED';
  end if;
  if exists(select 1 from public.schedule_lifecycle where year=p_year and month=p_month and state='final') then raise exception 'FINAL_SCHEDULE_IMMUTABLE'; end if;
  insert into public.schedule_lifecycle(year,month,state,swap_opened_at,swap_deadline,swap_closed_at,opened_by,finalized_at,finalized_by,final_json,final_backups,updated_at)
  values(p_year,p_month,'swap_open',now(),p_deadline,null,auth.uid(),null,null,null,null,now())
  on conflict(year,month) do update set state='swap_open',swap_opened_at=now(),swap_deadline=excluded.swap_deadline,swap_closed_at=null,opened_by=auth.uid(),finalized_at=null,finalized_by=null,final_json=null,final_backups=null,updated_at=now()
  returning * into v_row;
  return v_row;
end $$;

create or replace function public.close_swap_window_v2591(p_year integer,p_month integer)
returns public.schedule_lifecycle language plpgsql security definer set search_path=public,auth as $$
declare v_row public.schedule_lifecycle%rowtype;
begin
  if not public.is_operational_seniune_v2591(auth.uid()) then raise exception 'OPERATIONAL_SENIUNE_REQUIRED'; end if;
  update public.schedule_lifecycle set state='swap_closed',swap_closed_at=coalesce(swap_closed_at,now()),updated_at=now()
  where year=p_year and month=p_month and state='swap_open' returning * into v_row;
  if not found then raise exception 'SWAP_WINDOW_NOT_OPEN'; end if;
  return v_row;
end $$;

create or replace function public.grant_late_swap_access_v2591(
  p_year integer,p_month integer,p_initials text,p_expires_at timestamptz,
  p_max_requests integer default 1,p_access_mode text default 'one_request',p_reason text default ''
) returns public.late_swap_access language plpgsql security definer set search_path=public,auth as $$
declare v_row public.late_swap_access%rowtype;
begin
  if not public.is_operational_seniune_v2591(auth.uid()) then raise exception 'OPERATIONAL_SENIUNE_REQUIRED'; end if;
  if not exists(select 1 from public.schedule_lifecycle where year=p_year and month=p_month and state='swap_closed') then raise exception 'LATE_ACCESS_ONLY_AFTER_SWAP_WINDOW_CLOSED'; end if;
  if p_expires_at<=now() then raise exception 'LATE_ACCESS_EXPIRY_MUST_BE_FUTURE'; end if;
  if p_max_requests<1 or p_max_requests>20 then raise exception 'INVALID_MAX_REQUESTS'; end if;
  if p_access_mode not in ('one_request','time_window') then raise exception 'INVALID_ACCESS_MODE'; end if;
  if not exists(select 1 from public.resident_directory where initials=p_initials and active=true) then raise exception 'UNKNOWN_OR_INACTIVE_RESIDENT'; end if;
  update public.late_swap_access set revoked_at=now() where year=p_year and month=p_month and initials=p_initials and revoked_at is null and expires_at>now();
  insert into public.late_swap_access(year,month,initials,access_mode,max_requests,requests_used,expires_at,reason,granted_by)
  values(p_year,p_month,p_initials,p_access_mode,p_max_requests,0,p_expires_at,coalesce(p_reason,''),auth.uid()) returning * into v_row;
  return v_row;
end $$;

create or replace function public.revoke_late_swap_access_v2591(p_id bigint)
returns public.late_swap_access language plpgsql security definer set search_path=public,auth as $$
declare v_row public.late_swap_access%rowtype;
begin
  if not public.is_operational_seniune_v2591(auth.uid()) then raise exception 'OPERATIONAL_SENIUNE_REQUIRED'; end if;
  update public.late_swap_access set revoked_at=now() where id=p_id and revoked_at is null returning * into v_row;
  if not found then raise exception 'LATE_ACCESS_NOT_FOUND_OR_ALREADY_REVOKED'; end if;
  return v_row;
end $$;

-- Read-only permission check. Unlike submission, it NEVER consumes a late grant.
create or replace function public.get_swap_permission_v2591(p_year integer,p_month integer)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_me text; v_state text; v_deadline timestamptz; v_g public.late_swap_access%rowtype;
begin
  select initials into v_me from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_me is null then return jsonb_build_object('allowed',false,'source','unlinked'); end if;
  select state,swap_deadline into v_state,v_deadline from public.schedule_lifecycle where year=p_year and month=p_month;
  if v_state is null then return jsonb_build_object('allowed',false,'source','not_open','state','draft'); end if;
  if v_state='final' then return jsonb_build_object('allowed',false,'source','final','state','final'); end if;
  if v_state='swap_open' and v_deadline is not null and now()<=v_deadline then return jsonb_build_object('allowed',true,'source','window','state',v_state,'deadline',v_deadline); end if;
  select * into v_g from public.late_swap_access where year=p_year and month=p_month and initials=v_me and revoked_at is null and expires_at>now() and requests_used<max_requests order by expires_at asc,id asc limit 1;
  if found then return jsonb_build_object('allowed',true,'source','late','state',v_state,'grant_id',v_g.id,'expires_at',v_g.expires_at,'max_requests',v_g.max_requests,'requests_used',v_g.requests_used,'remaining',v_g.max_requests-v_g.requests_used); end if;
  return jsonb_build_object('allowed',false,'source',case when v_state='swap_open' then 'expired' else 'closed' end,'state',v_state,'deadline',v_deadline);
end $$;

create or replace function public._consume_late_swap_access_v2591(p_year integer,p_month integer,p_initials text)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare v_id bigint;
begin
  select id into v_id from public.late_swap_access where year=p_year and month=p_month and initials=p_initials and revoked_at is null and expires_at>now() and requests_used<max_requests order by expires_at asc,id asc for update skip locked limit 1;
  if v_id is null then return false; end if;
  update public.late_swap_access set requests_used=requests_used+1 where id=v_id;
  return true;
end $$;

create or replace function public._swap_submission_allowed_v2591(p_year integer,p_month integer,p_initials text)
returns boolean language plpgsql security definer set search_path=public,auth as $$
declare v_state text; v_deadline timestamptz;
begin
  select state,swap_deadline into v_state,v_deadline from public.schedule_lifecycle where year=p_year and month=p_month for update;
  if v_state is null or v_state='final' then return false; end if;
  if v_state='swap_open' and v_deadline is not null and now()<=v_deadline then return true; end if;
  return public._consume_late_swap_access_v2591(p_year,p_month,p_initials);
end $$;

create or replace function public.create_swap_request_v2591(p_year integer,p_month integer,p_slot_a integer,p_slot_b integer,p_person_a text,p_person_b text,p_reason text default '')
returns setof public.swap_requests language plpgsql security definer set search_path=public,auth as $$
declare v_me text; v_row public.swap_requests%rowtype;
begin
  select initials into v_me from public.user_profiles where user_id=auth.uid() and approved=true;
  if v_me is null or v_me<>p_person_a then raise exception 'SWAP_REQUESTER_IDENTITY_MISMATCH'; end if;
  if p_person_a=p_person_b then raise exception 'SWAP_SELF_NOT_ALLOWED'; end if;
  if not public._swap_submission_allowed_v2591(p_year,p_month,p_person_a) then raise exception 'SWAP_WINDOW_CLOSED'; end if;
  insert into public.swap_requests(year,month,slot_a,slot_b,person_a,person_b,status,reason) values(p_year,p_month,p_slot_a,p_slot_b,p_person_a,p_person_b,'pending',coalesce(p_reason,'')) returning * into v_row;
  return next v_row;
end $$;

create or replace function public.create_backup_swap_request_v2591(p_year integer,p_month integer,p_requester text,p_requester_slot integer,p_target text,p_target_slot integer,p_note text default '')
returns setof public.backup_swap_requests language plpgsql security definer set search_path=public,auth as $$
declare v_me text; v_row public.backup_swap_requests%rowtype;
begin
  select initials into v_me from public.user_profiles where user_id=auth.uid() and approved=true;
  if v_me is null or v_me<>p_requester then raise exception 'SWAP_REQUESTER_IDENTITY_MISMATCH'; end if;
  if p_requester=p_target then raise exception 'SWAP_SELF_NOT_ALLOWED'; end if;
  if not public._swap_submission_allowed_v2591(p_year,p_month,p_requester) then raise exception 'SWAP_WINDOW_CLOSED'; end if;
  insert into public.backup_swap_requests(year,month,requester,requester_slot,target,target_slot,status,note) values(p_year,p_month,p_requester,p_requester_slot,p_target,p_target_slot,'pending',coalesce(p_note,'')) returning * into v_row;
  return next v_row;
end $$;

-- New swaps must go through the lifecycle RPCs; direct INSERT is no longer an escape hatch.
drop policy if exists "swap own insert" on public.swap_requests;
drop policy if exists "backup swaps requester insert" on public.backup_swap_requests;

create or replace function public.finalization_blockers_v2591(p_year integer,p_month integer)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_state text; a int; b int; c int; d int;
begin
  select state into v_state from public.schedule_lifecycle where year=p_year and month=p_month;
  select count(*) into a from public.swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into b from public.swap_requests where year=p_year and month=p_month and status='approved' and coalesce(reason,'') like '%accepted_pending_senior_apply%';
  select count(*) into c from public.backup_swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into d from public.late_swap_access where year=p_year and month=p_month and revoked_at is null and expires_at>now() and requests_used<max_requests;
  return jsonb_build_object('state',coalesce(v_state,'none'),'pending_normal',a,'waiting_senior_apply',b,'pending_backup',c,'active_late_grants',d,'clear',(v_state='swap_closed' and a=0 and b=0 and c=0 and d=0));
end $$;

create or replace function public.finalize_schedule_v2591(p_year integer,p_month integer,p_final_json jsonb)
returns public.schedule_lifecycle language plpgsql security definer set search_path=public,auth as $$
declare v_row public.schedule_lifecycle%rowtype; v_b jsonb; v_current jsonb; v_backups jsonb;
begin
  if not public.is_operational_seniune_v2591(auth.uid()) then raise exception 'OPERATIONAL_SENIUNE_REQUIRED'; end if;
  select current_json into v_current from public.schedules where year=p_year and month=p_month and status='published' for update;
  if v_current is null then raise exception 'CURRENT_SCHEDULE_REQUIRED'; end if;
  -- The client submits what it just fully validated; require exact equality to the authoritative ACTUAL row.
  if p_final_json is distinct from v_current then raise exception 'FINAL_SNAPSHOT_STALE'; end if;
  v_b:=public.finalization_blockers_v2591(p_year,p_month);
  if coalesce((v_b->>'clear')::boolean,false)=false then raise exception 'FINALIZATION_BLOCKED:%',v_b::text; end if;
  select coalesce(jsonb_agg(to_jsonb(b) order by b.covered_slot),'[]'::jsonb) into v_backups from public.backup_assignments b where b.year=p_year and b.month=p_month;
  update public.schedule_lifecycle set state='final',swap_closed_at=coalesce(swap_closed_at,now()),finalized_at=now(),finalized_by=auth.uid(),final_json=v_current,final_backups=v_backups,updated_at=now() where year=p_year and month=p_month and state='swap_closed' returning * into v_row;
  if not found then raise exception 'SWAP_WINDOW_MUST_BE_CLOSED_BEFORE_FINAL'; end if;
  return v_row;
end $$;

grant execute on function public.open_swap_window_v2591(integer,integer,timestamptz) to authenticated;
grant execute on function public.close_swap_window_v2591(integer,integer) to authenticated;
grant execute on function public.grant_late_swap_access_v2591(integer,integer,text,timestamptz,integer,text,text) to authenticated;
grant execute on function public.revoke_late_swap_access_v2591(bigint) to authenticated;
grant execute on function public.get_swap_permission_v2591(integer,integer) to authenticated;
grant execute on function public.create_swap_request_v2591(integer,integer,integer,integer,text,text,text) to authenticated;
grant execute on function public.create_backup_swap_request_v2591(integer,integer,text,integer,text,integer,text) to authenticated;
grant execute on function public.finalization_blockers_v2591(integer,integer) to authenticated;
grant execute on function public.finalize_schedule_v2591(integer,integer,jsonb) to authenticated;

-- Reset integration: clear lifecycle/late grants before FINAL; never erase an administration FINAL.
create or replace function public.reset_month_schedule_v2522(p_year integer, p_month integer)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_uid uuid:=auth.uid(); v_initials text; v_is_senior boolean:=false; v_backup_ids bigint[]; v_cover_events integer:=0;
  v_schedules integer:=0; v_backups integer:=0; v_swaps integer:=0; v_backup_swaps integer:=0; v_repairs integer:=0; v_fairness integer:=0; v_lifecycle integer:=0; v_late integer:=0;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select up.initials into v_initials from public.user_profiles up where up.user_id=v_uid and up.approved=true limit 1;
  if v_initials is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  select public.is_senior(v_uid) into v_is_senior;
  if not v_is_senior then raise exception 'SENIOR_ONLY'; end if;
  if p_year<2026 or p_month<1 or p_month>12 then raise exception 'INVALID_MONTH'; end if;
  if exists(select 1 from public.schedule_lifecycle where year=p_year and month=p_month and state='final') then raise exception 'RESET_BLOCKED_FINAL_SCHEDULE'; end if;
  select coalesce(array_agg(id),array[]::bigint[]) into v_backup_ids from public.backup_assignments where year=p_year and month=p_month;
  if coalesce(array_length(v_backup_ids,1),0)>0 then select count(*) into v_cover_events from public.backup_cover_events where backup_id=any(v_backup_ids); end if;
  if v_cover_events>0 then raise exception 'RESET_BLOCKED_COMPLETED_BACKUP_ACTIVITY'; end if;
  delete from public.late_swap_access where year=p_year and month=p_month; get diagnostics v_late=row_count;
  delete from public.schedule_lifecycle where year=p_year and month=p_month; get diagnostics v_lifecycle=row_count;
  delete from public.schedule_repairs where year=p_year and month=p_month; get diagnostics v_repairs=row_count;
  delete from public.backup_swap_requests where year=p_year and month=p_month; get diagnostics v_backup_swaps=row_count;
  delete from public.swap_requests where year=p_year and month=p_month; get diagnostics v_swaps=row_count;
  delete from public.backup_assignments where year=p_year and month=p_month; get diagnostics v_backups=row_count;
  delete from public.fairness_history where year=p_year and month=p_month; get diagnostics v_fairness=row_count;
  delete from public.schedules where year=p_year and month=p_month; get diagnostics v_schedules=row_count;
  return jsonb_build_object('ok',true,'year',p_year,'month',p_month,'reset_by',v_initials,'schedules_deleted',v_schedules,'backups_deleted',v_backups,'swap_requests_deleted',v_swaps,'backup_swap_requests_deleted',v_backup_swaps,'repairs_deleted',v_repairs,'fairness_rows_deleted',v_fairness,'lifecycle_deleted',v_lifecycle,'late_access_deleted',v_late,'preferences_preserved',true,'recurring_preferences_preserved',true,'credit_redemptions_preserved',true);
end;
$$;
