-- V2.5.93 operator notification email admin + manual override review checkpoint

create table if not exists public.resident_email_admin_audit (
  id bigint generated by default as identity primary key,
  initials text not null references public.resident_directory(initials),
  old_email text not null default '',
  new_email text not null,
  source text not null default 'manual',
  actor_user_id uuid not null,
  actor_initials text not null,
  created_at timestamptz not null default now()
);

alter table public.resident_email_admin_audit enable row level security;
drop policy if exists "email admin operator read" on public.resident_email_admin_audit;
create policy "email admin operator read" on public.resident_email_admin_audit
for select to authenticated using (public.is_lifecycle_operator_v2592(auth.uid()));

grant select on public.resident_email_admin_audit to authenticated;

create or replace function public.set_resident_notification_email_v2593(
  p_initials text, p_email text
) returns jsonb
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_actor text; v_old text; v_email text:=lower(trim(coalesce(p_email,'')));
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  select initials into v_actor from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_actor is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  if not exists(select 1 from public.resident_directory where initials=p_initials and active=true) then raise exception 'UNKNOWN_OR_INACTIVE_RESIDENT'; end if;
  if v_email='' or v_email !~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' then raise exception 'INVALID_EMAIL'; end if;
  select coalesce(email,'') into v_old from public.account_settings where initials=p_initials for update;
  if not found then raise exception 'ACCOUNT_SETTINGS_NOT_FOUND'; end if;
  update public.account_settings set email=v_email,updated_at=now() where initials=p_initials;
  insert into public.resident_email_admin_audit(initials,old_email,new_email,source,actor_user_id,actor_initials)
  values(p_initials,coalesce(v_old,''),v_email,'manual',auth.uid(),v_actor);
  return jsonb_build_object('ok',true,'initials',p_initials,'email',v_email,'actor',v_actor);
end $$;

grant execute on function public.set_resident_notification_email_v2593(text,text) to authenticated;

create or replace function public.autofill_notification_emails_v2593()
returns jsonb
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_actor text; r record; v_count int:=0;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  select initials into v_actor from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_actor is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  for r in
    select a.initials,coalesce(a.email,'') old_email,
           lower(trim(coalesce(nullif(up.email,''),au.email,''))) login_email
    from public.account_settings a
    join public.resident_directory rd on rd.initials=a.initials and rd.active=true
    left join public.user_profiles up on up.initials=a.initials and up.approved=true
    left join auth.users au on au.id=up.user_id
    where coalesce(trim(a.email),'')=''
  loop
    if r.login_email<>'' and r.login_email ~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' then
      update public.account_settings set email=r.login_email,updated_at=now() where initials=r.initials;
      insert into public.resident_email_admin_audit(initials,old_email,new_email,source,actor_user_id,actor_initials)
      values(r.initials,r.old_email,r.login_email,'login_autofill',auth.uid(),v_actor);
      v_count:=v_count+1;
    end if;
  end loop;
  return jsonb_build_object('ok',true,'filled',v_count,'actor',v_actor);
end $$;

grant execute on function public.autofill_notification_emails_v2593() to authenticated;

alter table public.manual_schedule_overrides add column if not exists before_json jsonb;
alter table public.manual_schedule_overrides add column if not exists after_json jsonb;
alter table public.manual_schedule_overrides add column if not exists reviewed_at timestamptz;
alter table public.manual_schedule_overrides add column if not exists reviewed_by uuid;
alter table public.manual_schedule_overrides add column if not exists reviewed_by_initials text;

-- Existing overrides predate the checkpoint and must not retroactively block a month.
update public.manual_schedule_overrides
set reviewed_at=coalesce(reviewed_at,created_at), reviewed_by=coalesce(reviewed_by,actor_user_id), reviewed_by_initials=coalesce(reviewed_by_initials,actor_initials)
where reviewed_at is null;

create or replace function public.apply_manual_schedule_override_v2592(
  p_year integer, p_month integer, p_current_json jsonb,
  p_slot_a integer, p_slot_b integer, p_person_a text, p_person_b text, p_reason text default ''
) returns public.manual_schedule_overrides
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_actor text; v_state text; v_before jsonb; v_row public.manual_schedule_overrides%rowtype;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  select initials into v_actor from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_actor is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  if p_slot_a=p_slot_b or p_person_a=p_person_b then raise exception 'INVALID_MANUAL_SWAP'; end if;
  if coalesce(trim(p_reason),'')='' then raise exception 'MANUAL_OVERRIDE_REASON_REQUIRED'; end if;

  select current_json into v_before from public.schedules
  where year=p_year and month=p_month and status='published'
    and baseline_json is not null and current_json is not null
  for update;
  if v_before is null then raise exception 'PUBLISHED_SYSTEM_REQUIRED'; end if;

  select state into v_state from public.schedule_lifecycle where year=p_year and month=p_month for update;
  if v_state='final' then raise exception 'FINAL_SCHEDULE_IMMUTABLE'; end if;
  if v_state is null then
    insert into public.schedule_lifecycle(year,month,state,updated_at) values(p_year,p_month,'working',now());
  elsif v_state='draft' then
    update public.schedule_lifecycle set state='working',updated_at=now() where year=p_year and month=p_month;
  end if;

  update public.schedules set current_json=p_current_json,updated_at=now()
  where year=p_year and month=p_month and status='published';

  update public.swap_requests
  set status='rejected',
      reason=jsonb_build_object('kind','operator_override','phase','superseded','actor',v_actor,'at',now(),'note','slot changed by operator manual override')::text
  where year=p_year and month=p_month
    and (slot_a in (p_slot_a,p_slot_b) or slot_b in (p_slot_a,p_slot_b))
    and (status='pending' or (status='approved' and coalesce(reason,'') like '%accepted_pending_senior_apply%'));

  update public.backup_swap_requests
  set status='rejected',note=concat_ws(' | ',nullif(note,''),'superseded by operator manual override')
  where year=p_year and month=p_month
    and (requester_slot in (p_slot_a,p_slot_b) or target_slot in (p_slot_a,p_slot_b))
    and status='pending';

  insert into public.manual_schedule_overrides(
    year,month,slot_a,slot_b,person_a,person_b,reason,actor_user_id,actor_initials,
    before_json,after_json,reviewed_at,reviewed_by,reviewed_by_initials
  ) values(
    p_year,p_month,p_slot_a,p_slot_b,p_person_a,p_person_b,trim(p_reason),auth.uid(),v_actor,
    v_before,p_current_json,null,null,null
  ) returning * into v_row;
  return v_row;
end $$;

create or replace function public.review_manual_override_v2593(p_id bigint)
returns public.manual_schedule_overrides
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_actor text; v_row public.manual_schedule_overrides%rowtype;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  select initials into v_actor from public.user_profiles where user_id=auth.uid() and approved=true limit 1;
  if v_actor is null then raise exception 'APPROVED_PROFILE_REQUIRED'; end if;
  update public.manual_schedule_overrides
  set reviewed_at=now(),reviewed_by=auth.uid(),reviewed_by_initials=v_actor
  where id=p_id and reviewed_at is null
  returning * into v_row;
  if not found then
    select * into v_row from public.manual_schedule_overrides where id=p_id;
    if not found then raise exception 'MANUAL_OVERRIDE_NOT_FOUND'; end if;
  end if;
  return v_row;
end $$;

grant execute on function public.review_manual_override_v2593(bigint) to authenticated;

create or replace function public.finalization_blockers_v2591(p_year integer,p_month integer)
returns jsonb language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_state text; a int; b int; c int; d int; e int;
begin
  select state into v_state from public.schedule_lifecycle where year=p_year and month=p_month;
  select count(*) into a from public.swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into b from public.swap_requests where year=p_year and month=p_month and status='approved' and coalesce(reason,'') like '%accepted_pending_senior_apply%';
  select count(*) into c from public.backup_swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into d from public.late_swap_access where year=p_year and month=p_month and revoked_at is null and expires_at>now() and requests_used<max_requests;
  select count(*) into e from public.manual_schedule_overrides where year=p_year and month=p_month and reviewed_at is null;
  return jsonb_build_object('state',coalesce(v_state,'none'),'pending_normal',a,'waiting_senior_apply',b,'pending_backup',c,'active_late_grants',d,'unreviewed_manual_overrides',e,'clear',(v_state in ('working','swap_closed','swap_open') and a=0 and b=0 and c=0 and d=0 and e=0));
end $$;

create or replace function public.open_swap_window_v2591(p_year integer,p_month integer,p_deadline timestamptz)
returns public.schedule_lifecycle
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_row public.schedule_lifecycle%rowtype;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  if p_deadline<=now() then raise exception 'SWAP_DEADLINE_MUST_BE_FUTURE'; end if;
  if exists(select 1 from public.manual_schedule_overrides where year=p_year and month=p_month and reviewed_at is null) then raise exception 'UNREVIEWED_MANUAL_OVERRIDES_EXIST'; end if;
  if not exists(select 1 from public.schedules s where s.year=p_year and s.month=p_month and s.status='published' and s.baseline_json is not null and s.current_json is not null) then raise exception 'PUBLISHED_SYSTEM_REQUIRED'; end if;
  if exists(select 1 from public.schedule_lifecycle l where l.year=p_year and l.month=p_month and l.state='final') then raise exception 'FINAL_SCHEDULE_IMMUTABLE'; end if;
  insert into public.schedule_lifecycle(year,month,state,swap_opened_at,swap_deadline,swap_closed_at,opened_by,finalized_at,finalized_by,final_json,updated_at)
  values(p_year,p_month,'swap_open',now(),p_deadline,null,auth.uid(),null,null,null,now())
  on conflict(year,month) do update set state='swap_open',swap_opened_at=now(),swap_deadline=excluded.swap_deadline,swap_closed_at=null,opened_by=auth.uid(),finalized_at=null,finalized_by=null,final_json=null,updated_at=now()
  returning * into v_row;
  return v_row;
end $$;

create or replace function public.finalize_schedule_v2592(p_year integer,p_month integer,p_final_json jsonb)
returns public.schedule_lifecycle
language plpgsql security definer
set search_path to 'public','auth'
as $$
declare v_row public.schedule_lifecycle%rowtype; v_state text;
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then raise exception 'LIFECYCLE_OPERATOR_REQUIRED'; end if;
  if not exists(select 1 from public.schedules s where s.year=p_year and s.month=p_month and s.status='published' and s.baseline_json is not null and s.current_json is not null) then raise exception 'PUBLISHED_SYSTEM_REQUIRED'; end if;
  select state into v_state from public.schedule_lifecycle where year=p_year and month=p_month for update;
  if v_state is null then insert into public.schedule_lifecycle(year,month,state,updated_at) values(p_year,p_month,'working',now()); v_state:='working'; end if;
  if v_state='final' then raise exception 'FINAL_SCHEDULE_IMMUTABLE'; end if;
  if exists(select 1 from public.manual_schedule_overrides where year=p_year and month=p_month and reviewed_at is null) then raise exception 'UNREVIEWED_MANUAL_OVERRIDES_EXIST'; end if;
  if exists(select 1 from public.late_swap_access where year=p_year and month=p_month and revoked_at is null and expires_at>now() and requests_used<max_requests) then raise exception 'ACTIVE_LATE_SWAP_ACCESS_EXISTS'; end if;
  if exists(select 1 from public.swap_requests where year=p_year and month=p_month and status='pending') then raise exception 'PENDING_SWAP_REQUESTS_EXIST'; end if;
  if exists(select 1 from public.swap_requests where year=p_year and month=p_month and status='approved' and coalesce(reason,'') like '%accepted_pending_senior_apply%') then raise exception 'SWAPS_AWAITING_OPERATOR_APPLY'; end if;
  if exists(select 1 from public.backup_swap_requests where year=p_year and month=p_month and status='pending') then raise exception 'PENDING_BACKUP_SWAP_REQUESTS_EXIST'; end if;
  update public.schedule_lifecycle set state='final',swap_closed_at=coalesce(swap_closed_at,now()),finalized_at=now(),finalized_by=auth.uid(),final_json=p_final_json,
      final_backups=coalesce((select jsonb_agg(to_jsonb(b) order by b.covered_slot) from public.backup_assignments b where b.year=p_year and b.month=p_month),'[]'::jsonb),updated_at=now()
  where year=p_year and month=p_month returning * into v_row;
  return v_row;
end $$;
