-- V2.5.111 — ADMIN WATERFILL + WESTON + SR FINAL SWAP GATE
-- Additive/idempotent migration. Scheduling/fairness data is not rewritten.

-- -------------------------------------------------------------------------
-- A. Persistent WESTON beer joke ledger for SR generation clicks.
-- -------------------------------------------------------------------------
create table if not exists public.weston_beer_ledger_v25110 (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    initials text not null references public.resident_directory(initials) on update cascade on delete cascade,
    cycle_year integer not null check (cycle_year between 2026 and 2100),
    cycle_month integer not null check (cycle_month between 1 and 12),
    action text not null default 'generate' check (action = 'generate'),
    created_at timestamptz not null default now(),
    check (initials = 'SR')
);
create index if not exists weston_beer_ledger_v25110_user_idx on public.weston_beer_ledger_v25110(user_id, created_at);
create index if not exists weston_beer_ledger_v25110_cycle_idx on public.weston_beer_ledger_v25110(cycle_year, cycle_month, created_at);
alter table public.weston_beer_ledger_v25110 enable row level security;
drop policy if exists weston_beer_ledger_v25110_self_select on public.weston_beer_ledger_v25110;
create policy weston_beer_ledger_v25110_self_select on public.weston_beer_ledger_v25110
for select to authenticated using (user_id = auth.uid());

create or replace function public.record_weston_beer_click_v25110(p_cycle_year integer,p_cycle_month integer)
returns table(total_beers bigint, month_beers bigint)
language plpgsql security definer set search_path=public,auth as $$
declare v_uid uuid:=auth.uid(); v_initials text;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  if v_initials is distinct from 'SR' then raise exception 'WESTON_LEDGER_SR_ONLY' using errcode='42501'; end if;
  if p_cycle_year<2026 or p_cycle_year>2100 or p_cycle_month<1 or p_cycle_month>12 then raise exception 'INVALID_CYCLE'; end if;
  insert into public.weston_beer_ledger_v25110(user_id,initials,cycle_year,cycle_month,action)
  values(v_uid,'SR',p_cycle_year,p_cycle_month,'generate');
  return query select count(*)::bigint,
      count(*) filter(where w.cycle_year=p_cycle_year and w.cycle_month=p_cycle_month)::bigint
    from public.weston_beer_ledger_v25110 w where w.user_id=v_uid;
end $$;

create or replace function public.weston_beer_stats_v25110(p_cycle_year integer,p_cycle_month integer)
returns table(total_beers bigint, month_beers bigint)
language plpgsql security definer set search_path=public,auth as $$
declare v_uid uuid:=auth.uid(); v_initials text;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  if v_initials is distinct from 'SR' then raise exception 'WESTON_LEDGER_SR_ONLY' using errcode='42501'; end if;
  return query select count(*)::bigint,
      count(*) filter(where w.cycle_year=p_cycle_year and w.cycle_month=p_cycle_month)::bigint
    from public.weston_beer_ledger_v25110 w where w.user_id=v_uid;
end $$;
revoke all on function public.record_weston_beer_click_v25110(integer,integer) from public;
revoke all on function public.weston_beer_stats_v25110(integer,integer) from public;
grant execute on function public.record_weston_beer_click_v25110(integer,integer) to authenticated;
grant execute on function public.weston_beer_stats_v25110(integer,integer) to authenticated;

-- -------------------------------------------------------------------------
-- B. Explicit SR final decision audit for both normal and backup swaps.
-- -------------------------------------------------------------------------
alter table public.swap_requests add column if not exists senior_decision text;
alter table public.swap_requests add column if not exists senior_decided_at timestamptz;
alter table public.swap_requests add column if not exists senior_decided_by uuid references auth.users(id);

do $$ begin
  alter table public.swap_requests add constraint swap_requests_senior_decision_chk
    check (senior_decision is null or senior_decision in ('approved','declined'));
exception when duplicate_object then null; end $$;

alter table public.backup_swap_requests add column if not exists participant_accepted_at timestamptz;
alter table public.backup_swap_requests add column if not exists participant_accepted_by uuid references auth.users(id);
alter table public.backup_swap_requests add column if not exists senior_decision text;
alter table public.backup_swap_requests add column if not exists senior_decided_at timestamptz;
alter table public.backup_swap_requests add column if not exists senior_decided_by uuid references auth.users(id);

do $$ begin
  alter table public.backup_swap_requests add constraint backup_swap_requests_senior_decision_chk
    check (senior_decision is null or senior_decision in ('approved','declined'));
exception when duplicate_object then null; end $$;

-- Target resident accepts a backup swap, but this intentionally DOES NOT mutate
-- backup_assignments. ACTUAL changes only after SR approves.
create or replace function public.accept_backup_swap_participant_v25111(p_request_id bigint)
returns public.backup_swap_requests
language plpgsql security definer set search_path=public,auth as $$
declare r public.backup_swap_requests%rowtype; v_uid uuid:=auth.uid(); v_initials text;
begin
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  select * into r from public.backup_swap_requests where id=p_request_id for update;
  if not found then raise exception 'BACKUP_SWAP_NOT_FOUND'; end if;
  if r.status<>'pending' then raise exception 'BACKUP_SWAP_NOT_PENDING'; end if;
  if v_initials is distinct from r.target then raise exception 'BACKUP_SWAP_ACCEPT_NOT_AUTHORIZED' using errcode='42501'; end if;
  update public.backup_swap_requests
     set participant_accepted_at=now(), participant_accepted_by=v_uid
   where id=r.id returning * into r;
  return r;
end $$;

-- SR must be the exact operational leader account, not a generic admin/researcher.
create or replace function public.approve_backup_swap_by_sr_v25111(p_request_id bigint)
returns public.backup_swap_requests
language plpgsql security definer set search_path=public,auth as $$
declare r public.backup_swap_requests%rowtype; v_uid uuid:=auth.uid(); v_initials text;
begin
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  if v_initials is distinct from 'SR' then raise exception 'SR_ONLY' using errcode='42501'; end if;
  select * into r from public.backup_swap_requests where id=p_request_id for update;
  if not found then raise exception 'BACKUP_SWAP_NOT_FOUND'; end if;
  if r.status<>'pending' then raise exception 'BACKUP_SWAP_NOT_PENDING'; end if;
  if r.participant_accepted_at is null then raise exception 'BOTH_RESIDENTS_NOT_CONSENTED'; end if;
  perform public.accept_backup_swap(p_request_id);
  update public.backup_swap_requests
     set senior_decision='approved',senior_decided_at=now(),senior_decided_by=v_uid
   where id=p_request_id returning * into r;
  return r;
end $$;

create or replace function public.reject_backup_swap_by_sr_v25111(p_request_id bigint)
returns public.backup_swap_requests
language plpgsql security definer set search_path=public,auth as $$
declare r public.backup_swap_requests%rowtype; v_uid uuid:=auth.uid(); v_initials text;
begin
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  if v_initials is distinct from 'SR' then raise exception 'SR_ONLY' using errcode='42501'; end if;
  select * into r from public.backup_swap_requests where id=p_request_id for update;
  if not found then raise exception 'BACKUP_SWAP_NOT_FOUND'; end if;
  if r.status<>'pending' then raise exception 'BACKUP_SWAP_NOT_PENDING'; end if;
  update public.backup_swap_requests
     set status='rejected',responded_at=now(),senior_decision='declined',senior_decided_at=now(),senior_decided_by=v_uid
   where id=r.id returning * into r;
  return r;
end $$;

create or replace function public.mark_normal_swap_sr_decision_v25111(p_request_id bigint,p_decision text)
returns public.swap_requests
language plpgsql security definer set search_path=public,auth as $$
declare r public.swap_requests%rowtype; v_uid uuid:=auth.uid(); v_initials text; v_dec text:=lower(trim(coalesce(p_decision,'')));
begin
  select initials into v_initials from public.user_profiles where user_id=v_uid and approved=true limit 1;
  if v_initials is distinct from 'SR' then raise exception 'SR_ONLY' using errcode='42501'; end if;
  if v_dec not in ('approved','declined') then raise exception 'INVALID_SR_DECISION'; end if;
  select * into r from public.swap_requests where id=p_request_id for update;
  if not found then raise exception 'SWAP_NOT_FOUND'; end if;
  if v_dec='declined' then
    if r.status<>'approved' then raise exception 'RESIDENT_CONSENT_NOT_COMPLETE'; end if;
    update public.swap_requests set status='rejected',senior_decision='declined',senior_decided_at=now(),senior_decided_by=v_uid
      where id=r.id returning * into r;
  else
    if r.status<>'approved' then raise exception 'SWAP_NOT_APPROVED_BY_RESIDENTS'; end if;
    update public.swap_requests set senior_decision='approved',senior_decided_at=now(),senior_decided_by=v_uid
      where id=r.id returning * into r;
  end if;
  return r;
end $$;

revoke all on function public.accept_backup_swap_participant_v25111(bigint) from public;
revoke all on function public.approve_backup_swap_by_sr_v25111(bigint) from public;
revoke all on function public.reject_backup_swap_by_sr_v25111(bigint) from public;
revoke all on function public.mark_normal_swap_sr_decision_v25111(bigint,text) from public;
grant execute on function public.accept_backup_swap_participant_v25111(bigint) to authenticated;
grant execute on function public.approve_backup_swap_by_sr_v25111(bigint) to authenticated;
grant execute on function public.reject_backup_swap_by_sr_v25111(bigint) to authenticated;
grant execute on function public.mark_normal_swap_sr_decision_v25111(bigint,text) to authenticated;

-- Finalization continues to block until every proposed swap is fully resolved.
create or replace function public.finalization_blockers_v2591(p_year integer,p_month integer)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_state text; a int; b int; c int; d int; e int;
begin
  select state into v_state from public.schedule_lifecycle where year=p_year and month=p_month;
  select count(*) into a from public.swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into b from public.swap_requests where year=p_year and month=p_month and status='approved'
    and coalesce(reason,'') like '%accepted_pending_senior_apply%' and coalesce(senior_decision,'')<>'approved';
  select count(*) into c from public.backup_swap_requests where year=p_year and month=p_month and status='pending';
  select count(*) into d from public.late_swap_access where year=p_year and month=p_month and revoked_at is null and expires_at>now() and requests_used<max_requests;
  select count(*) into e from public.manual_schedule_overrides where year=p_year and month=p_month and reviewed_at is null;
  return jsonb_build_object('state',coalesce(v_state,'none'),'pending_normal',a,'waiting_senior_apply',b,'pending_backup',c,'active_late_grants',d,'unreviewed_manual_overrides',e,'clear',(v_state in ('working','swap_closed','swap_open') and a=0 and b=0 and c=0 and d=0 and e=0));
end $$;
