-- V2.5.128 — privatus SP + ŠR planavimo sluoksnis.
-- Šios eilutės sąmoningai NEPATEKIA į viešą rezidentų pageidavimų auditą,
-- taisyklių langą, Excel eksportą ar pristatymo vadovą.
-- Detales gali matyti tik patvirtintos SP ir ŠR paskyros.

create table if not exists public.operator_private_pair_preferences_v25128 (
  id bigint generated by default as identity primary key,
  owner_initials text not null references public.resident_directory(initials) on delete cascade,
  year integer not null,
  month integer not null check (month between 1 and 12),
  preference_type text not null check (preference_type in ('together','apart')),
  target_initials text not null references public.resident_directory(initials) on delete cascade,
  scope_type text not null check (scope_type in ('month','week','day')),
  scope_start_date date null,
  block text not null default 'ANY' check (block in ('ANY','AM','PM')),
  workplace text not null default 'ANY' check (workplace in ('ANY','CENTRO RO','Onko RO','SPS RO','Centro UG','SPS UG','ADC 144','ADC 145','Vaikų UG','Mamografijos')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (owner_initials in ('SP','ŠR')),
  check (target_initials <> owner_initials),
  check (
    (scope_type='month' and scope_start_date is null)
    or (scope_type in ('week','day') and scope_start_date is not null)
  )
);

create index if not exists idx_operator_private_pair_month_v25128
  on public.operator_private_pair_preferences_v25128(year,month,owner_initials);

create unique index if not exists operator_private_pair_unique_v25128
on public.operator_private_pair_preferences_v25128(
  owner_initials,year,month,preference_type,target_initials,scope_type,
  coalesce(scope_start_date,date '1900-01-01'),block,workplace
);

create table if not exists public.operator_private_pair_preference_audit_v25128 (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null,
  actor_user_id uuid null,
  actor_initials text not null,
  owner_initials text not null,
  action text not null check (action in ('create','delete')),
  preference_id bigint null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Perkelti ankstesnius SP privačius pageidavimus, jei V2.5.123 jau buvo paleista.
do $$
begin
  if to_regclass('public.sp_private_pair_preferences_v25123') is not null then
    insert into public.operator_private_pair_preferences_v25128(
      owner_initials,year,month,preference_type,target_initials,scope_type,scope_start_date,block,workplace,created_at,updated_at
    )
    select
      'SP',year,month,preference_type,target_initials,scope_type,scope_start_date,block,workplace,created_at,updated_at
    from public.sp_private_pair_preferences_v25123
    on conflict do nothing;
  end if;
end $$;

alter table public.operator_private_pair_preferences_v25128 enable row level security;
alter table public.operator_private_pair_preference_audit_v25128 enable row level security;

-- SP ir ŠR gali matyti privatų operatorių sluoksnį. Kitos paskyros — nieko.
drop policy if exists "operator private pair select" on public.operator_private_pair_preferences_v25128;
create policy "operator private pair select" on public.operator_private_pair_preferences_v25128
for select to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials in ('SP','ŠR')
  )
);

-- Įrašymas per RPC. Tiesioginis insert/update/delete uždaromas paprastoms užklausoms.
drop policy if exists "operator private pair insert" on public.operator_private_pair_preferences_v25128;
create policy "operator private pair insert" on public.operator_private_pair_preferences_v25128
for insert to authenticated
with check (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials=owner_initials and up.initials in ('SP','ŠR')
  )
);

drop policy if exists "operator private pair update" on public.operator_private_pair_preferences_v25128;
create policy "operator private pair update" on public.operator_private_pair_preferences_v25128
for update to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials=owner_initials and up.initials in ('SP','ŠR')
  )
)
with check (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials=owner_initials and up.initials in ('SP','ŠR')
  )
);

drop policy if exists "operator private pair delete" on public.operator_private_pair_preferences_v25128;
create policy "operator private pair delete" on public.operator_private_pair_preferences_v25128
for delete to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials=owner_initials and up.initials in ('SP','ŠR')
  )
);

drop policy if exists "operator private pair audit select" on public.operator_private_pair_preference_audit_v25128;
create policy "operator private pair audit select" on public.operator_private_pair_preference_audit_v25128
for select to authenticated
using (
  exists (
    select 1 from public.user_profiles up
    where up.user_id=(select auth.uid()) and up.approved=true and up.initials in ('SP','ŠR')
  )
);

create or replace function public.operator_create_private_pair_preference_v25128(
  p_year integer,
  p_month integer,
  p_preference_type text,
  p_target_initials text,
  p_scope_type text,
  p_scope_start_date date,
  p_block text,
  p_workplace text
)
returns public.operator_private_pair_preferences_v25128
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare
  v_uid uuid:=auth.uid();
  v_actor text;
  v_row public.operator_private_pair_preferences_v25128%rowtype;
  v_month_start date:=make_date(p_year,p_month,1);
  v_month_end date:=(make_date(p_year,p_month,1)+interval '1 month - 1 day')::date;
begin
  select up.initials into v_actor
  from public.user_profiles up
  where up.user_id=v_uid and up.approved=true
  limit 1;

  if v_actor not in ('SP','ŠR') then raise exception 'PRIVATE_OPERATOR_ONLY'; end if;
  if p_target_initials=v_actor or not exists(
      select 1 from public.resident_directory rd where rd.initials=p_target_initials and coalesce(rd.active,true)=true
  ) then raise exception 'INVALID_PRIVATE_PAIR_TARGET'; end if;
  if p_preference_type not in ('together','apart') then raise exception 'INVALID_PRIVATE_PAIR_TYPE'; end if;
  if p_scope_type not in ('month','week','day') then raise exception 'INVALID_PRIVATE_PAIR_SCOPE'; end if;
  if coalesce(p_block,'ANY') not in ('ANY','AM','PM') then raise exception 'INVALID_PRIVATE_PAIR_BLOCK'; end if;
  if coalesce(p_workplace,'ANY') not in ('ANY','CENTRO RO','Onko RO','SPS RO','Centro UG','SPS UG','ADC 144','ADC 145','Vaikų UG','Mamografijos') then
    raise exception 'INVALID_PRIVATE_PAIR_WORKPLACE';
  end if;
  if p_scope_type='month' and p_scope_start_date is not null then raise exception 'MONTH_SCOPE_DATE_MUST_BE_NULL'; end if;
  if p_scope_type in ('week','day') then
    if p_scope_start_date is null then raise exception 'PRIVATE_PAIR_SCOPE_DATE_REQUIRED'; end if;
    if p_scope_start_date < v_month_start or p_scope_start_date > v_month_end then raise exception 'PRIVATE_PAIR_SCOPE_DATE_OUTSIDE_MONTH'; end if;
  end if;

  insert into public.operator_private_pair_preferences_v25128(
    owner_initials,year,month,preference_type,target_initials,scope_type,scope_start_date,block,workplace
  ) values(
    v_actor,p_year,p_month,p_preference_type,p_target_initials,p_scope_type,p_scope_start_date,
    coalesce(p_block,'ANY'),coalesce(p_workplace,'ANY')
  ) returning * into v_row;

  insert into public.operator_private_pair_preference_audit_v25128(
    year,month,actor_user_id,actor_initials,owner_initials,action,preference_id,payload
  ) values(
    p_year,p_month,v_uid,v_actor,v_actor,'create',v_row.id,to_jsonb(v_row)
  );
  return v_row;
end;
$$;

create or replace function public.operator_delete_private_pair_preference_v25128(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path to 'public','auth'
as $$
declare
  v_uid uuid:=auth.uid();
  v_actor text;
  v_row public.operator_private_pair_preferences_v25128%rowtype;
begin
  select up.initials into v_actor
  from public.user_profiles up
  where up.user_id=v_uid and up.approved=true
  limit 1;
  if v_actor not in ('SP','ŠR') then raise exception 'PRIVATE_OPERATOR_ONLY'; end if;

  select * into v_row
  from public.operator_private_pair_preferences_v25128
  where id=p_id
  for update;
  if not found then return false; end if;
  if v_row.owner_initials is distinct from v_actor then raise exception 'PRIVATE_PREFERENCE_NOT_OWNER'; end if;

  delete from public.operator_private_pair_preferences_v25128 where id=p_id;
  insert into public.operator_private_pair_preference_audit_v25128(
    year,month,actor_user_id,actor_initials,owner_initials,action,preference_id,payload
  ) values(
    v_row.year,v_row.month,v_uid,v_actor,v_row.owner_initials,'delete',v_row.id,to_jsonb(v_row)
  );
  return true;
end;
$$;

-- Tik egzistavimo signalas bendram lifecycle kodui; jokių detalių.
create or replace function public.operator_private_pair_preferences_exist_v25128(p_year integer,p_month integer)
returns boolean
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $$
begin
  if not public.is_lifecycle_operator_v2592(auth.uid()) then return false; end if;
  return exists(
    select 1 from public.operator_private_pair_preferences_v25128
    where year=p_year and month=p_month
  );
end;
$$;

grant select on table public.operator_private_pair_preferences_v25128 to authenticated;
grant select on table public.operator_private_pair_preference_audit_v25128 to authenticated;
grant execute on function public.operator_create_private_pair_preference_v25128(integer,integer,text,text,text,date,text,text) to authenticated;
grant execute on function public.operator_delete_private_pair_preference_v25128(bigint) to authenticated;
grant execute on function public.operator_private_pair_preferences_exist_v25128(integer,integer) to authenticated;

-- ŠR turi mokėti PERSKAITYTI SP Dream Team tikslus generavimo metu, kad abu
-- operatoriai gautų tą patį privatų refinement sluoksnį. Keisti juos ir toliau gali tik SP.
drop policy if exists "sp dream config select" on public.sp_dream_team_config_v25125;
create policy "sp dream config select" on public.sp_dream_team_config_v25125
for select to authenticated using (
  exists(select 1 from public.user_profiles up where up.user_id=(select auth.uid()) and up.approved=true and up.initials in ('SP','ŠR'))
);

drop policy if exists "sp dream monthly select" on public.sp_dream_team_monthly_v25125;
create policy "sp dream monthly select" on public.sp_dream_team_monthly_v25125
for select to authenticated using (
  exists(select 1 from public.user_profiles up where up.user_id=(select auth.uid()) and up.approved=true and up.initials in ('SP','ŠR'))
);
