-- V2.5.100 — durable notification outbox for lifecycle emails.
-- Additive migration: no existing schedule/email data is removed.

create table if not exists public.notification_outbox (
    id bigint generated by default as identity primary key,
    event_key text not null,
    event_type text not null,
    initials text not null references public.resident_directory(initials) on update cascade on delete cascade,
    target_year integer not null,
    target_month integer not null check (target_month between 1 and 12),
    scheduled_for timestamptz not null default now(),
    to_email text not null default '',
    subject text not null,
    body text not null,
    ics_text text,
    ics_name text,
    status text not null default 'pending' check (status in ('pending','sent','failed','blocked')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    last_error text,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(event_key, initials)
);

create index if not exists notification_outbox_due_idx
    on public.notification_outbox(status, scheduled_for);
create index if not exists notification_outbox_cycle_idx
    on public.notification_outbox(target_year, target_month, event_type, status);

alter table public.notification_outbox enable row level security;

drop policy if exists notification_outbox_operator_select on public.notification_outbox;
create policy notification_outbox_operator_select
on public.notification_outbox for select
to authenticated
using (public.is_lifecycle_operator_v2592(auth.uid()));

drop policy if exists notification_outbox_operator_insert on public.notification_outbox;
create policy notification_outbox_operator_insert
on public.notification_outbox for insert
to authenticated
with check (public.is_lifecycle_operator_v2592(auth.uid()));

drop policy if exists notification_outbox_operator_update on public.notification_outbox;
create policy notification_outbox_operator_update
on public.notification_outbox for update
to authenticated
using (public.is_lifecycle_operator_v2592(auth.uid()))
with check (public.is_lifecycle_operator_v2592(auth.uid()));

-- A resident does not need direct access to the shared delivery outbox.
-- Service-role background workers bypass RLS and may process pending rows.
